Misc. improvements, unit tests and mypy proofing
remiolsen/anglerfish pull request #85
Opened 2024-06-12 12:04 UTC by kedhammar

2024-06-17 11:42 UTC, alneberg commented on tests/test_anglerfish/test_demux/test_adaptor.py
> +    assert to_test.validate_adaptors(valid_adaptors_dict) is None
A bit counter intuitive that None is good. I think I would have preferred that this method returns True when everything is OK. Not a big deal though

2024-06-17 11:49 UTC, alneberg commented on tests/test_anglerfish/test_demux/test_demux.py
> +    Creats a temporary directory with...
```suggestion
    Creates a temporary directory with...
```

2024-06-17 12:21 UTC, alneberg commented
I think it looks good! Let me know when it's not in draft mode.

2024-06-18 13:54 UTC, kedhammar commented on tests/test_anglerfish/test_demux/test_adaptor.py
> +    assert to_test.validate_adaptors(valid_adaptors_dict) is None
The method itself doesn't actually return anything (which is only implicitly evaluated as None), it throws an error if the assertion fails. I explicitly check that it doesn't return anything here in case the output of the function changes in the future.

2024-06-18 13:57 UTC, kedhammar commented on tests/test_anglerfish/test_demux/test_adaptor.py
> +    assert to_test.validate_adaptors(valid_adaptors_dict) is None
Nevertheless, c4c832b73092b9a17da30c54ade0ff9eb21d99b0

2024-06-18 13:58 UTC, kedhammar commented
Still need to fix CI-errors, but code is ready for review.

2024-06-25 07:56 UTC, alneberg commented on tests/test_anglerfish/test_demux/test_adaptor.py
> +    assert to_test.validate_adaptors(valid_adaptors_dict) is None
Haha, I was actually willing to agree with you, but Ok!

2024-06-25 09:01 UTC, alneberg approved these changes
👍 according to previous comment.

2024-06-26 09:42 UTC, remiolsen requested changes
This is very nice work.

2024-06-26 11:55 UTC, kedhammar commented on tests/test_anglerfish/test_demux/test_demux.py
> +                "q": 25,
To be addressed in future PR, stay tuned ⏳

2024-06-26 11:56 UTC, remiolsen approved these changes
Re-reviewing this as approved since requested changes is invalidated by another PR.

2024-06-26 11:56 UTC, merged

2024-07-02 10:14 UTC, kedhammar commented on tests/test_anglerfish/test_demux/test_demux.py
> +                "q": 25,
[337a20a](https://github.com/remiolsen/anglerfish/pull/86/commits/337a20a45fa568490700edb043994ed98d9070ce)